#!/bin/bash

# Netplugd Startup Script

. /etc/rc.d/init.d/functions

case "$1" in
start)
	echo -n "Starting netplugd: "
	netplugd
	check_status
	;;
stop)
	echo -n "Stopping netplugd: "
	killall netplugd
	check_status
	;;
restart)
	$0 stop
	$0 start
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
