#!/bin/bash
#
# installation-help for DRACOS
# 22.05.2007
#
# shell script for installation of DRACOS to harddisk
#
# written by Thomas Schoenhuetl <pilleus.pulcher@arcor.de> 22.05.2007
# modfification by purnomo hadi and edo Maland
# It contains parts of the official Slackware installer.
#
# This shell script is contributed under the terms of GPL v2 by Thomas Schoenhuetl <pilleus.pulcher@arcor.de> 22.05.2007.
#
#Installer dracOs Linux  Gnu/Linux version 2.0
#www.dutalinux.org

#www.dracos-linux.org
#Code name leak

setterm --reset

#####################################################
# SOME COLOURS BIAR COOL
#####################################################
cyan='\e[0;36m'
green='\e[0;34m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'
BlueF='\e[1;34m'


######################################################
#Some Variable
#echo -e "Holla  \e[0m"

####################################################
####################################################

clear

dialog --clear --backtitle "dracOs `uname -m` GNU/Linux installer "  --title " -- Dracos Linux -- " --colors --msgbox "\ZB\Z1             80G08        \n                8G#G@8  \n                  8##0  \n                   0##G8    \n                     ####08 \n                      8#####8   \n                        G#####8   \n                         8G#####8   \n      #8#########0         #######8   \n          8#######0          0#88#####  \n            8G####8         8 8#8@@8###   \n               8###        G8   8@G######   \n                8##88       8     8######8    \n                  G##088          80G##G080   \n                    88000000008880#      000    \n                          9               0 \n\n\n\ZB\Z1      =[ \ZB\Z1Dracos Linux\ZB\Z7 : \ZB\Z7All Developer Team \ZB\Z1]=\n\n\ZB\Z1   [(c) \ZB\Z72016-2017 \ZB\Z1|\ZB\Z7 dracos-linux.org \ZB\Z1|\ZB\Z7 gauli.net " 30 55

dialog --clear --backtitle "dracOs `uname -m` GNU/Linux installer "  --title " -- ABOUT -- " --colors --msgbox "\n\ZB\Z7DracOs Linux is the Linux operating system from \ZB\Z1Indonesia \ZB\Z7Open source is built based on the \ZB\Z1Linux From Scratch \ZB\Z7under the protection of the \ZB\Z1GNU General Public License v3.0.\n\n\ZB\Z7This operating system is one variant of Linux distributions, which is used to perform \ZB\Z1security testing \ZB\Z7(penetration testing).\n\nDracos linux in Arm by hundreds hydraulic pentest, forensics and reverse engineering. Does not use a \ZB\Z1GUI-based \ZB\Z7tools-tools and just have the software using the \ZB\Z1CLI (command line interface) \ZB\Z7to perform its operations. Now Dracos currently already up to \ZB\Z1version 2.0 \ZB\Z7with the code name \ZB\Z1Leak.\n\n\ZB\Z7Website :\ZB\Z1https://www.dracos-linux.org \n\n\ZB\Z7Forum :\ZB\Z1https://forum.dracos-linux.org \n\n\ZB\Z7OurTeam :\ZB\Z1https://dracos-linux.org/team/  " 23 75
mkdir /tmp/DRACOS/ 2>/dev/null

dialog --clear --backtitle "dracOs `uname -m` GNU/Linux installer "  --title "-- GENERAL INFORMATION --" --colors --yesno "\n\ZB\Z7 Dracos Installer is a curses based tool to \ZB\Z1install \ZB\Z7your running Dracos to your \ZB\Z1harddisk.\n\n\ZB\Z7 You are able to \ZB\Z1partition and format your harddisk and install in the end a bootloader.\n\n\ZB\Z7 You will use this installer at your \ZB\Z1own risk.\ZB\Z7 I am not responsible for \ZB\Z1lost of datas or something else.\n\n\ZB\Z7 If you \ZB\Z1accept \ZB\Z7this, you can \ZB\Z1start now! \ZB\Z7Or you may cancel the installer!" 20 110
if [ $? = 1 ] ; then
exit
fi

dialog --clear --backtitle "dracOs `uname -m` GNU/Linux installer "  --title "-- Time Zone --" --colors --yesno "\n Do you want to set time Zone " 10 40
if [ $? = 0 ] ; then
clear
      
    		rm /timezone


tzselect | tee -a /timezone
	
clear

cp -v /usr/share/zoneinfo/`cat /timezone` /etc/localtime
fi
sleep 2 

dialog --clear --backtitle "dracOs `uname -m` GNU/Linux installer "  --title "-- ROOT password --" --colors --yesno "\n Do you want to change root password   " 10 40
if [ $? = 0 ] ; then
clear
passwd root 
fi

# umount harddisk for running cfdisk
umount /mnt/* 2>/dev/null

# run cfdisk to partition the harddrive
dialog --clear --backtitle "dracOs `uname -m` GNU/Linux installer "  --title "-- PARTITION THE HARDDISK --" --colors --yesno "\n\ZB\Z7Dracos installer will now start \ZB\Z1cfdisk\ZB\Z7 so that you are able to \ZB\Z1create new \ZB\Z7partitions for Dracos.\n\n\ZB\Z7Two partitions are recommended. [1] for the \ZB\Z1system\ZB\Z7 and [1] for \ZB\Z1SWAP.\n\n\ZB\Z7I think \ZB\Z115 GB\ZB\Z7 are enough for the root-partition - Dracos plus additional programs - and twice the amount of your \ZB\Z1RAM for the swap-partition.\n\n\ZB\Z7Just follow the menu, store your changes and quit cfdisk to go on!\n\n\ZB\Z1	IMPORTANT: Read the instructions and the output of cfdisk carefully. Sometimes you have to reboot to update the partition table!" 20 110
if [ $? = 1 ] ; then
exit
fi

# Create partitions using fdisk or cfdisk.
echo expert-mode >> /etc/expert-mode
mkdir /tmp/tmp 2>/dev/null
TMP=/tmp/tmp 2>/dev/null

fdisk -l | sed -n 's/^Disk \(\/dev\/[^:]*\): \([^,]*\).*$/"\1" "\2" \\/p' >> $TMP/drivelist

while [ 0 ]; do
  echo dialog --ok-label Select \
    --cancel-label Continue \
    --title \"PARTITIONING\" \
    --menu \"Select drive to partition:\" 11 40 4 \\\
    > $TMP/tmpscript
  cat $TMP/drivelist >> $TMP/tmpscript
  echo "2> $TMP/tmpanswer" >> $TMP/tmpscript
  . $TMP/tmpscript
  [ $? != 0 ] && break
  PARTITION=`cat $TMP/tmpanswer`

  if [ ! -f /etc/expert-mode ]; then
    cfdisk $PARTITION
  else
    echo dialog --title \"PARTITIONING $PARTITION\" \
      --menu \"Select which fdisk program you want to use. cfdisk is \
      strongly recommended for newbies while advanced users may prefer fdisk.\" \
      15 60 3 \
      cfdisk \"Curses based partitioning program\" \
      fdisk \"Traditional fdisk\" \
      "2> $TMP/tmpanswer" > $TMP/tmpscript
    . $TMP/tmpscript
    [ $? != 0 ] && continue
    FDISKPROGRAM=`cat $TMP/tmpanswer`
    clear
    if [ "$FDISKPROGRAM" = "cfdisk" ]; then
      cfdisk $PARTITION
    elif [ "$FDISKPROGRAM" = "fdisk" ]; then
      fdisk $PARTITION
    fi
  fi
done
rm -f $TMP/drivelist $TMP/tmpscript $TMP/tmpanswer




TMP=/tmp/tmp
if [ ! -d $TMP ]; then
  mkdir -p $TMP
fi
REDIR=/dev/tty4
NDIR=/dev/null
crunch() {
 read STRING;
 echo $STRING;
}
##################
#  SWAP removed  #
#  error lbgmp   #
##################

# format root partition
fdisk -l | grep Linux | sed -e '/swap/d' | cut -b 1-9 > $TMP/pout 2>/dev/null
partprobe `cat $TMP/pout |  cut -b 1-8` 


dialog --clear --backtitle "dracOs `uname -m` GNU/Linux installer "  --title " -- ROOT PARTITION DETECTED -- " --exit-label OK  --colors --msgbox "\n\n\ZB\Z1Dracos \ZB\Z7installer has \ZB\Z1detected\n\n `cat /tmp/tmp/pout` \n\nas your \ZB\Z1linux partition(s).\n\n\ZB\Z7In the next box you can \ZB\Z1choose the linux filesystem\ZB\Z7 for your \ZB\Z1root partition \ZB\Z7or choose the partition if you have more \ZB\Z1linux partitions!" 20 80
if [ $? = 1 ] ; then
exit
fi

# choose root partition
dialog --clear --backtitle "dracOs `uname -m` GNU/Linux installer "  --title " -- CHOOSE ROOT PARTITION -- " --colors --inputbox "\n\n\ZB\Z7Please give me your preferred \ZB\Z1root partition \ZB\Z7in this way:\n\n\ZB\Z7Write /dev/hdax \n\ZB\Z1Example : \ZB\Z72 for \ZB\Z1/dev/hda2 \n\nNOTE : \n\ZB\Z7x :\ZB\Z7 Number of the partition\n\n\n " 20 80 2> $TMP/pout

dialog --clear --backtitle "dracOs `uname -m` GNU/Linux installer "  --title " -- FORMAT ROOT PARTITION -- " --radiolist "Now you can choose the filesystem for your root partition.\n\n ReiserFS is the recommended filesystem. to /mnt/`cat $TMP/pout | cut -b 6-9`/" 10 70 0 \
"1" "ext2" off \
"2" "ext3" off \
"3" "ext4" on \
"4" "reiserfs" of \
2> $TMP/part
if [ $? = 1 ] ; then
exit
fi

if [ `cat $TMP/part` = "1" ] ; then
mkfs.ext2 `cat $TMP/pout`
dialog --clear --backtitle "dracOs `uname -m` GNU/Linux installer "  --title " -- FORMAT ROOT PARTITION -- " --colors --msgbox "\n\n\ZB\Z7Now your partition has been formatted with \ZB\Z1\ext2 filesystem." 10 70
echo "`cat $TMP/pout` / ext2 defaults,noatime 1 1" >> $TMP/SeTfstab2
# mount the root partition to copy the system
mkdir /mnt/`cat $TMP/pout | cut -b 6-9`
mount -t ext2 /dev/`cat $TMP/pout | cut -b 6-9` /mnt/`cat $TMP/pout | cut -b 6-9`
fi

if [ `cat $TMP/part` = "2" ] ; then
mkfs.ext3 `cat $TMP/pout`
dialog --clear --backtitle "dracOs `uname -m` GNU/Linux installer "  --title " -- FORMAT ROOT PARTITION -- " --colors --msgbox "\n\n\ZB\Z7Now your partition has been formatted with \ZB\Z1\ext3 filesystem." 10 70
echo "`cat $TMP/pout` / ext3 defaults,noatime 1 1" >> $TMP/SeTfstab2
# mount the root partition to copy the system
mkdir /mnt/`cat $TMP/pout | cut -b 6-9`
mount -t ext3 /dev/`cat $TMP/pout | cut -b 6-9` /mnt/`cat $TMP/pout | cut -b 6-9`
fi

if [ `cat $TMP/part` = "3" ] ; then
mkfs.ext4 `cat $TMP/pout`
dialog --clear --backtitle "dracOs `uname -m` GNU/Linux installer "  --title " -- FORMAT ROOT PARTITION -- " --colors --msgbox "\n\n\ZB\Z7Now your partition has been formatted with \ZB\Z1\ext4 filesystem." 10 70
echo "`cat $TMP/pout` / ext4 defaults,noatime 1 1" >> $TMP/SeTfstab2
# mount the root partition to copy the system
mkdir /mnt/`cat $TMP/pout | cut -b 6-9`
mount -t ext4 /dev/`cat $TMP/pout | cut -b 6-9` /mnt/`cat $TMP/pout | cut -b 6-9`
fi

if [ `cat $TMP/part` = "4" ] ; then
mkfs.reiserfs -f `cat $TMP/pout`
dialog --clear --backtitle "dracOs `uname -m` GNU/Linux installer "  --title " -- FORMAT ROOT PARTITION -- " --colors --msgbox "\n\n\ZB\Z7Now your partition has been formatted with \ZB\Z1reiserfs filesystem." 10 70
echo "`cat $TMP/pout` / reiserfs defaults,noatime 1 1" >> $TMP/SeTfstab2
# mount the root partition to copy the system
mkdir /mnt/`cat $TMP/pout | cut -b 6-9`
mount -t reiserfs /dev/`cat $TMP/pout | cut -b 6-9` /mnt/`cat $TMP/pout | cut -b 6-9`
fi

# copy the system
dialog --clear --backtitle "dracOs `uname -m` GNU/Linux installer "  --title " -- COPYING THE SYSTEM -- " --colors --msgbox "\n\n\ZB\Z7Dracos Installer will now copy the running system to \ZB\Z1your harddisk.\n\n\ZB\Z7Press OK to start ..." 10 70
if [ $? = 1 ] ; then
exit
fi



###############################
DIRS=( /bin /boot /opt /usr /etc /home /lib /root /sbin /srv  /var  /lib64)

# Destination directory
#DEST="/tmp/test.$$"

# Create $DEST if does not exits
#[ ! -d $DEST ] && mkdir -p $DEST

#
# Show a progress bar
# ---------------------------------
# Redirect dialog commands input using substitution
#
dialog --title "Copy file" --gauge "Copying file..." 10 75 < <(
   # Get total number of files in array
   n=${#DIRS[*]};

   # set counter - it will increase every-time a file is copied to $DEST
   i=0

   #
   # Start the for loop
   #
   # read each file from $DIRS array
   # $f has filename
   for f in "${DIRS[@]}"
   do
      # calculate progress
      PCT=$(( 100*(++i)/n ))

      # update dialog box
cat <<EOF
XXX
$PCT
Copying file "$f" ...
XXX
EOF
  # copy file $f to $DEST
  cp  --preserve -R $f /mnt/`cat $TMP/pout | cut -b 6-9`/ &>/dev/null
   done
)
################################

#cp  --preserve -R  /{bin,boot,etc,home,lib,root,sbin,srv,usr,var,opt,lib64} /mnt/`cat $TMP/pout | cut -b 6-9`/ 2>/dev/null
#rsync -pavr /mnt/live/memory/bundles/root.sfs/*  /mnt/`cat $TMP/pout | cut -b 6-9`/ 2>/dev/null
mkdir /mnt/`cat $TMP/pout | cut -b 6-9`/dev 2>/dev/null
mkdir /mnt/`cat $TMP/pout | cut -b 6-9`/dev/pts 2>/dev/null
mkdir /mnt/`cat $TMP/pout | cut -b 6-9`/mnt 2>/dev/null
mkdir /mnt/`cat $TMP/pout | cut -b 6-9`/proc 2>/dev/null
mkdir /mnt/`cat $TMP/pout | cut -b 6-9`/sys 2>/dev/null
mkdir /mnt/`cat $TMP/pout | cut -b 6-9`/tmp 2>/dev/null
mkdir /mnt/`cat $TMP/pout | cut -b 6-9`/run 2>/dev/null


#cp /mnt/live/mnt/*/boot/vmlinuz /mnt/`cat $TMP/pout | cut -b 6-9`/boot/ 2>/dev/null

dialog --clear --backtitle "dracOs `uname -m` GNU/Linux installer "  --title " -- TRANSACTION FINISHED -- " --colors --msgbox "\n\n\ZB\Z7Now Dracos Installer has finished the transaction." 10 70
if [ $? = 1 ] ; then
exit
fi

# create new fstab
echo `cat $TMP/SeTfstab` > /mnt/`cat $TMP/pout | cut -b 6-9`/etc/fstab 2>/dev/null
echo `cat $TMP/SeTfstab2` >> /mnt/`cat $TMP/pout | cut -b 6-9`/etc/fstab 2>/dev/null

echo "proc /proc proc nosuid,noexec,nodev 0 0" >> /mnt/`cat $TMP/pout | cut -b 6-9`/etc/fstab 2>/dev/null
echo "sysfs /sys sysfs nosuid,noexec,nodev 0 0" >> /mnt/`cat $TMP/pout | cut -b 6-9`/etc/fstab 2>/dev/null
echo "devpts /dev/pts devpts gid=5,mode=620 0 0" >> /mnt/`cat $TMP/pout | cut -b 6-9`/etc/fstab 2>/dev/null
echo "tmpfs /run tmpfs defaults 0 0" >> /mnt/`cat $TMP/pout | cut -b 6-9`/etc/fstab 2>/dev/null
echo "devtmpfs /dev devtmpfs mode=0755,nosuid 0 0" >> /mnt/`cat $TMP/pout | cut -b 6-9`/etc/fstab 2>/dev/null



# prepare installation of grub
mount --bind /dev /mnt/`cat $TMP/pout | cut -b 6-9`/dev
mount -t proc /proc /mnt/`cat $TMP/pout | cut -b 6-9`/proc

mount -vt devpts -o gid=5,mode=620 devpts /mnt/`cat $TMP/pout | cut -b 6-9`/dev/pts
mount -vt tmpfs tmpfs /mnt/`cat $TMP/pout | cut -b 6-9`/run
mount -vt sysfs sysfs /mnt/`cat $TMP/pout | cut -b 6-9`/sys
cp --preserve -R /etc/grub.d.deb/* /mnt/`cat $TMP/pout | cut -b 6-9`/etc/grub.d/ 2>/dev/null
cp -f /.bashrc  /mnt/`cat $TMP/pout | cut -b 6-9`/root/.bashrc

dialog --clear --backtitle "dracOs `uname -m` GNU/Linux installer "  --title " -- Installing GRUB Boot loader -- " --colors --radiolist "\n\n\ZB\Z7Now you can choose \ZB\Z1install grub \ZB\Z7or if you have \ZB\Z1grub before\ZB\Z7 and use it please select \ZB\Z1no .to /mnt/`cat $TMP/pout | cut -b 6-9`/" 10 70 0 \
"1" "yes" on \
"2" "no" off \
2> $TMP/part2
if [ $? = 1 ] ; then
exit
fi

  if [ `cat $TMP/part2` = "1" ] ; then

    dialog --backtitle "dracOs `uname -m` GNU/Linux installer "  --title " -- Installing GRUB Boot loader -- " --colors --msgbox "\n\n\ZB\Z1 Grub-install `cat $TMP/pout |  cut -b 1-8` --force --boot-directory=/mnt/`cat $TMP/pout |  cut -b 6-9`/boot" 10 75

    grub-install `cat $TMP/pout |  cut -b 1-8` --force --boot-directory=/mnt/`cat $TMP/pout |  cut -b 6-9`/boot

     ################################################
     # remove uneeded grub my be make stuck on boot #
     ################################################
     rm -vf /mnt/`cat $TMP/pout |  cut -b 6-9`/etc/grub.d/*xen
     rm -vf /etc/grub.d/*xen

    chroot /mnt/`cat $TMP/pout |  cut -b 6-9` /sbin/grub-mkconfig -o /boot/grub/grub.cfg
   # chroot /mnt/`cat $TMP/pout |  cut -b 6-9` /usr/sbin/grub-mkconfig -o /boot/grub/grub.cfg

  fi
  if [ `cat $TMP/part2` = "2" ] ; then

    dialog --clear --backtitle "dracOs `uname -m` GNU/Linux installer "  --title "-- INSTALLATION FINISHED -- " --colors --yesno "\n\n\ZB\Z7Now Dracos Installer has \ZB\Z1finished the installation.\ZB\Z7Please reboot the system to boot  another distro for \ZB\Z1generating new grub menu.\n\n\ZB\Z7Use \ZB\Z1sudo grub-mkconfig -o /boot/grub/grub.cfg to generate grub menu " 10 90
      if [ $? = 0 ] ; then
	clear
	reboot
      fi
  fi







dialog --clear --backtitle "dracOs `uname -m` GNU/Linux installer "  --title "-- INSTALLATION FINISHED -- " --colors --yesno "\n\n\ZB\Z7Now Dracos Installer has finished the installation.\n\nPlease \ZB\Z1reboot the system or continue testing  " 10 70
if [ $? = 0 ] ; then
clear
reboot
fi


rm -R $TMP

exit
