#!/bin/sh
# Initial script for kolomonggo-linux
# compare between linux live script & kolomonggo-init
# Author of linux live kit : Tomas M <http://www.linux-live.org/>
# Author of kolomonggo init: purnomo hadi <purnomo.shinigami@gmail.com>
# initswitch beetwen systemd and sysvinit only for kolomonggo linux system hyrarki 

export PATH=.:/:/usr/sbin:/usr/bin:/sbin:/bin


GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

. /lib/debuginit
. /lib/insinit
. /lib/livekitlib
. /lib/.config
. /lib/persistandmode
. /lib/syteminitswitch




transfer_initramfs



MEMORY=/memory
CHANGES=$MEMORY/changes
UNION=$MEMORY/union
DATAMNT=$MEMORY/data
BUNDLES=$MEMORY/bundles



############# end of all fuction #############




# mount virtual filesystems like proc etc
init_proc_sysfs

debug_start
init_devs

init_aufs
#init_zram

if grep -q clean  /proc/cmdline; then
  clear
fi

if [ -f "/kernel-modules.sfs" ];
then
echo " mount kernel module "

mount /kernel-modules.sfs /lib/modules

fi

if [ -f "/kernel-firmware.sfs" ];
then
echo " mount kernel module "

mount /kernel-firmware.sfs /lib/firmware

fi


if grep -q embeded  /proc/cmdline; then
/linuxrc
fi

######## run init for live $DISTNAME ###########



if grep -q live  /proc/cmdline; then

header "//$DISTNAME Live Kit init start"


  # find data dir with filesystem bundles
  DATA="$(find_data 60 "$DATAMNT")"
                                                                                                                                                      debug_shell
  # setup persistent changes, if possible
  persistent_changes "$DATA" "$CHANGES"
                                                                                                                                                      debug_shell
  # copy to RAM if needed
  DATA="$(copy_to_ram "$DATA" "$CHANGES")"
                                                                                                                                                      debug_shell
  # init aufs union
  init_union "$CHANGES" "$UNION"
                                                                                                                                                      debug_shell
  # add data to union
  union_append_bundles "$DATA" "$BUNDLES" "$UNION"
                                                                                                                                                      debug_shell
  # rootcopy
  copy_rootcopy_content "$DATA" "$UNION"

  # create empty fstab
  fstab_create "$UNION"
  
 # installer_ "$UNION"
         

	if grep -q install  /proc/cmdline; then
		
		header "// running installation tool via initramfs "
                cd $UNION

echo "//   Please wait ..." 
echo "//   creating manifest data "     
find * -type f > /data-manifest
echo "//   cleaning uneded did in manifest "               
sed -i '/dev/d' /data-manifest
sed -i '/proc/d' /data-manifest
sed -i '/sys/d' /data-manifest
sed -i '/run/d' /data-manifest
sed -i '/tmp/d' /data-manifest
echo "//    runing installer"
sleep 2

 /bin/installer
        elif grep -q recovery /proc/cmdline; then
                /linuxrc
	
        else
		header "// Live Kit done, starting $DISTNAME"

 	  	change_root "$UNION"
        fi



else

########################################################
######## end run init for live $DISTNAME ########
########################################################


#######################################################################
######## run init for $DISTNAME has already to installed ########
#######################################################################
header "//$DISTNAME init start"

# only work for kolomonggo linux hirarky
# OTHER LFS BASED DISTRO 


init_function
do_mount_root




header "//$DISTNAME init done, starting $DISTNAME"
exec switch_root /.root "$init" "$@"

fi
#######################################################################
######## end init for $DISTNAME has already to installed ########
#######################################################################

header "!!ERROR occured, you shouldn't be here.!!"
/bin/sh



