#!/bin/sh

# echo green star
#
echo_green_star()
{
   echo -ne "[0;39m""// ""[0;39m"
}



FILE_LIST="setsid mksquashfs rm cp mke2fs modprobe touch ldd lsblk cfdisk egrep mkntfs mkfs "




echo_green_star
echo -ne " copying som binary from system   >" | tr -s "/" >&2
for files in $FILE_LIST
do
      echo -ne ">" >&2
sleep 0.1

 if [ -e "/bin/$files" ]; then
        cp -v /bin/$files $TGT_TMP_INITRD/bin

elif [ -e "/sbin/$files" ]; then
        cp -v /sbin/$files $TGT_TMP_INITRD/bin

elif [ -e "/usr/bin/$files" ]; then
        cp -v /usr/bin/$files $TGT_TMP_INITRD/bin

elif [ -e "/usr/sbin/$files" ]; then
        cp -v /usr/sbin/$files $TGT_TMP_INITRD/bin


else 
    echo "$files File does not exist"  >/dev/null 2>/dev/null
fi 


done
echo ""







# cp  /bin/sh $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
# cp  /bin/bash $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
# cp  /bin/cat $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
# cp  /bin/mount $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
# cp  /bin/echo $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
  cp  /usr/bin/setsid $TGT_TMP_INITRD/usr/bin/ >/dev/null 2>/dev/null
  cp  /usr/bin/mksquashfs $TGT_TMP_INITRD/usr/bin/mksquashfs >/dev/null 2>/dev/null
  cp  /bin/rm $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
  cp  /bin/cp $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
  cp  /bin/mkdir  $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
  cp  /bin/ln  $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
 cp  /sbin/modprobe $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
  cp  /sbin/mkswap  $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
  cp  /sbin/swapon $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
  cp  /sbin/rmmod $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
  cp  /bin/find  $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
  cp  /bin/rmdir $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
# cp  /sbin/mke2fs $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
  cp  /usr/bin/touch  $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
  cp  /bin/chmod  $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
  cp  /usr/bin/ldd $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
  cp  /bin/ls $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
  cp  /bin/mv  $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
  cp  /bin/grep  $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
  cp  /bin/umount  $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
 # cp  /usr/sbin/chroot  $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
 # cp  /sbin/pivot_root $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
  # cp  /sbin/switch_root  $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
  cp  /bin/kill  $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
  cp  /usr/bin/printf  $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
  cp  /usr/bin/tr  $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
  cp  /usr/bin/cut $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
  cp  /bin/egrep $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
 #cp  /sbin/cfdisk $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
  cp  /bin/kmod $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
  cp  /usr/sbin/mkntfs $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null
  cp  /sbin/mkfs*  $TGT_TMP_INITRD/bin >/dev/null 2>/dev/null


  cp -pR /usr/bin/dialog $TGT_TMP_INITRD/usr/bin/ >/dev/null 2>/dev/null
  cp -pR /usr/lib/*dialog* $TGT_TMP_INITRD/usr/lib >/dev/null 2>/dev/null
# cp -pR /bin/lsblk $TGT_TMP_INITRD/bin/lsblk >/dev/null 2>/dev/null



LIB_LIST="libreadline  libhistory libdl libc ld librt"




echo_green_star
echo -ne " copying som binary from system   >" | tr -s "/" >&2
for libs in $LIB_LIST
do
      echo -ne ">" >&2
sleep 0.1

 if [ -e "/bin/$libs" ]; then
        cp -v /lib/$libs* $TGT_TMP_INITRD/lib

elif [ -e "/sbin/$libs" ]; then
        cp -v /lin64/$libs* $TGT_TMP_INITRD/lib

elif [ -e "/usr/bin/$libs" ]; then
        cp -v /usr/lib/$libs* $TGT_TMP_INITRD/lib

elif [ -e "/usr/sbin/$libs" ]; then
        cp -v /usr/lib/$libs* $TGT_TMP_INITRD/lb


else 
    echo "$libs File does not exist"  >/dev/null 2>/dev/null
fi 


done



echo "// copying some lib and app from system"

  cp -pR /lib/libreadline* $TGT_TMP_INITRD/lib >/dev/null 2>/dev/null
  cp -pR /lib/libhistory* $TGT_TMP_INITRD/lib >/dev/null 2>/dev/null
 # cp -pR /lib/libncurses* $TGT_TMP_INITRD/lib >/dev/null 2>/dev/null
  cp -pR /lib/libdl* $TGT_TMP_INITRD/lib >/dev/null 2>/dev/null
  cp -pR /lib/libc* $TGT_TMP_INITRD/lib >/dev/null 2>/dev/null
  cp -pR /lib64/ld* $TGT_TMP_INITRD/lib >/dev/null 2>/dev/null
 # cp -pR /lib/libmount* $TGT_TMP_INITRD/lib >/dev/null 2>/dev/null
 # cp -pR /lib/libblkid* $TGT_TMP_INITRD/lib >/dev/null 2>/dev/null
 # cp -pR /lib/libuuid* $TGT_TMP_INITRD/lib >/dev/null 2>/dev/null
  cp -pR /lib/librt* $TGT_TMP_INITRD/lib >/dev/null 2>/dev/null
  cp -pR /lib/libpthread* $TGT_TMP_INITRD/lib >/dev/null 2>/dev/null
  cp -pR /lib/libm* $TGT_TMP_INITRD/lib >/dev/null 2>/dev/null
  cp -pR /lib/libz* $TGT_TMP_INITRD/lib >/dev/null 2>/dev/null
  cp -pR /lib/liblzma* $TGT_TMP_INITRD/lib >/dev/null 2>/dev/null
  cp -pR /lib/libacl* $TGT_TMP_INITRD/lib >/dev/null 2>/dev/null
  cp -pR /lib/libattr* $TGT_TMP_INITRD/lib >/dev/null 2>/dev/null
  cp -pR /lib/libsmart* $TGT_TMP_INITRD/lib >/dev/null 2>/dev/null
 # cp -pR /lib/libext2fs* $TGT_TMP_INITRD/lib >/dev/null 2>/dev/null
  cp -pR /lib/libcom_err* $TGT_TMP_INITRD/lib  >/dev/null 2>/dev/null
 # cp -pR /lib/libe2p* $TGT_TMP_INITRD/lib >/dev/null 2>/dev/null
  cp -pR /lib/libcap* $TGT_TMP_INITRD/lib >/dev/null 2>/dev/null
 # cp -pR /lib/libfdisk* $TGT_TMP_INITRD/lib >/dev/null 2>/dev/null
  cp -pR /lib/libntfs* $TGT_TMP_INITRD/lib >/dev/null 2>/dev/null
  cp -pR /usr/lib/libcurl* $TGT_TMP_INITRD/lib >/dev/null 2>/dev/null
  cp -pR /usr/lib/libstdc* $TGT_TMP_INITRD/lib >/dev/null 2>/dev/null
  cp -pR /usr/lib/libgcc* $TGT_TMP_INITRD/lib >/dev/null 2>/dev/null