#!/bin/bash
dir_main="config pkg mnt err"

for dirmain in $dir_main
do 
	 if [ -L "$dirmain" ]; then
		 if [ -e "$dirmain" ]; then	
			echo "$dirmain is exist and it's a good simslynk"
		 else
			echo "$dirmain is exist and it's a broken simslynk"
		 fi
	 elif [ -e "$dirmain" ] ; then
	                echo "$dirmain exist but not a simslink"
         else 
			echo "not found"
	 fi
done


