#!/bin/sh
# Functions library :: for find where kolomonggo Linux is installed
# Author: purnomo hadi kolomonggolinux.pe.hu , http://dracos-linux.org/
# installation script



init_function()
{

   echo_green_star
   echo "read parameter from cmdline ..."

read -r cmdline < /proc/cmdline

for param in $cmdline ; do
  case $param in
    init=*      ) init=${param#init=}             ;;
    root=*      ) root=${param#root=}             ;;
    rootdelay=* ) rootdelay=${param#rootdelay=}   ;;
    rootfstype=*) rootfstype=${param#rootfstype=} ;;
    rootflags=* ) rootflags=${param#rootflags=}   ;;
    ro          ) ro="ro"                         ;;
    rw          ) ro="rw"                         ;;
  esac
done



}

udev_function()                      
{

   echo_green_star
   echo "find and runing udev..."


   # udevd location depends on version
   if [ -x /sbin/udevd ]; then
     UDEVD=/sbin/udevd
  elif [ -x /lib/udev/udevd ]; then
     UDEVD=/lib/udev/udevd
  elif [ -x /lib/systemd/systemd-udevd ]; then
     UDEVD=/lib/systemd/systemd-udevd
  else
     echo "Cannot find udevd nor systemd-udevd"
     problem
  fi

  ${UDEVD} --daemon --resolve-names=never
  udevadm trigger
  udevadm settle

  if [ -f /etc/mdadm.conf ] ; then mdadm -As                       ; fi
  if [ -x /sbin/vgchange  ] ; then /sbin/vgchange -a y > /dev/null ; fi
  if [ -n "$rootdelay"    ] ; then sleep "$rootdelay"              ; fi


}

do_mount_root()               
{
  echo_green_star
  echo "mount root partition"

   mkdir /.root
   [ -n "$rootflags" ] && rootflags="$rootflags,"
   rootflags="$rootflags$ro"

   case "$root" in
      /dev/* ) device=$root ;;
      UUID=* ) eval $root; device="/dev/disk/by-uuid/$UUID"  ;;
      LABEL=*) eval $root; device="/dev/disk/by-label/$LABEL" ;;
      ""     ) echo "No root device specified." ; problem    ;;
   esac

   while [ ! -b "$device" ] ; do
       no_device $device
       problem
   done

   if ! mount -n -t "$rootfstype" -o "$rootflags" "$device" /.root ; then
       no_mount $device
       cat /proc/partitions
       while true ; do sleep 10000 ; done
   else
       echo "Successfully mounted device $root"
   fi
}


init=/sbin/init
root=
rootdelay=
rootfstype=auto
ro="ro"
rootflags=
device=
#mount -n -t devtmpfs devtmpfs /dev
#mount -n -t proc     proc     /proc
#mount -n -t sysfs    sysfs    /sys
#mount -n -t tmpfs    tmpfs    /run


##############################################
######## installation script startted ########
##############################################