#!/bin/bash


#####################################################
# SOME COLOURS BIAR COOL
#####################################################
cyan='\e[0;36m'
green='\e[0;34m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'
BlueF='\e[1;34m'


SETUP_INITRD="no"
SETUP_REMASTERING="no"
SETUP_SOURCES="no"
SETUP_KERNEL="no"
SETUP_PREPARE="no"


ISOBURN="no"
SQUASHFS="no"
SUDOAPP="no"
WGETAPP="no"
GITAPP="no"
XTERMAPP="no"
AUFS_MODULE="no"



# echo green star
#
echo_green_star()
{
   echo -ne "[0;39m""// ""[0;39m"
}

